package:
  name: taxcalc
  version: 0.0.0

requirements:
  build:
    - python
    - "numpy>=1.13"
    - "pandas>=0.23"
    - numba

  run:
    - python
    - "numpy>=1.13"
    - "pandas>=0.23"
    - numba

about:
  home: http://www.github.com/TPRU-India
